import { defineCollections } from 'vuepress-theme-plume';

import {
  goCollection,
  vueCollection,
  rustCollection,
  nodeCollection,
  reactCollection,
  notesCollection,
  blogCollection,
  javascriptCollection,
  typescriptCollection,
  modularizationCollection,
  packageManagerCollection,
  babelCollection,
  viteCollection,
  gulpCollection,
  webpackCollection,
  rollupCollection,
  esbuildCollection,
} from './collections/index'

export default defineCollections([
  goCollection,
  vueCollection,
  rustCollection,
  nodeCollection,
  reactCollection,
  notesCollection,
  blogCollection,
  javascriptCollection,
  typescriptCollection,
  modularizationCollection,
  packageManagerCollection,
  babelCollection,
  viteCollection,
  gulpCollection,
  webpackCollection,
  rollupCollection,
  esbuildCollection,
]);
